### PR TITLE
add notebook on Galerkin OPs

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
I don't know why the file is so big though (17 MB).

### CODE REVIEW

**Comment by dlfivefifty** [comment]
What plot package did you use?

**Comment by MikaelSlevinsky** [comment]
The default... GR

**Comment by MikaelSlevinsky** [comment]
Maybe it's because of the use of the `size` keyword?

**Comment by dlfivefifty** [comment]
Yes must be, since I think GR produces pixels. 

Plotly may be better since I think it produces SVG/WebGL.

**Comment by MikaelSlevinsky** [comment]
Well now that I updated my PlotlyJS, I can't load IJulia without re-compiling an outdated version of ApproxFun (and vice versa). I've never seen this happen before!

I changed the example to a .jl script.

**Pull request merged**
